const mongoose = require('mongoose');

module.exports =  mongoose.model('ProjectData', {
  "rowId": Number,
  "Reviewed": String,
  "ProjectId": Number,
  "alien": Number,
  "rocket": Number,
  "globe": Number,
  "rainbow": Number,
  "lightbulb": Number,
  "Primary Image": String,
  "Timestamp": String,
  //"I confirm that this project meets the three requirements above. ": String,
  //"Adult Name (First & Last)": String,
  //"Adult Email Address": String,
  "School or Organization": String,
  //"Relationship to Student/s:": String,
  //"(Optional) Are there other email addresses we should include in outreach about this project?  List here separated by commas. ": String,
  "Project Name": String,
  "Project Description": String,
  "Student Names": String,
  "Age Range": String,
  "Project Category": String,
  "Organization or Program Affiliation": String,
  "Images": String,
  "Video": String,
  "Slides": String,
  "Links": String,
  "Audio": String,
  "More About Our Project": String,
  "Student Count": String,
  "Schools": String,
  "Award Name": String
});